version: 2
registries:
  npmjs:
    type: npm-registry
    url: https://registry.npmjs.org
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    version-resolver:
      npm:
        enabled: true
        package-ecosystem: "npm"
        directory: "/"
        script: "../version-resolver.js" # Relative path to your custom version resolver script
