version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    registries:
      npm:
        type: npm-registry
        url: https://registry.npmjs.com
    version-resolver:
      my-custom-resolver:
        type: npm
        script: ../version-resolver.js
