version: 2
registries:
    npmjs:
      type: npm-registry
      url: https://registry.npmjs.org
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
    version-resolver:
      my-custom-resolver:
        type: npm
        script: ../version-resolver.js
